### ISSUE TITLE
Lockfile not saved

### ISSUE THREAD

**Issue by rajnikantmrao** [mozilla/mr-social-client#209]
I have cloned this respository and when I am trying to `yarn install` it gives a message `info Lockfile not saved, no dependencies.`

Subsequently,  when I issue the `yarn start` command after moving to the `mr-social-client` directory, I get the followiwng error.

```
/bin/sh: cross-env: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The node version I am using is v9.3.0 on Mac OS X `0.13.3

Thanks

**Comment by robertlong** [comment]
Hey @rajnikantmrao make sure you are in the `mr-social-client` directory when you run `yarn install`

```
cd mr-social-client
yarn install
yarn start
```

Also there is currently not a great way to create a room locally.

You'll need to navigate to a URL like this:
```
https://<your-ip-here>:8080/hub.html?room=<some-room-id>
```

Ex:
```
https://192.168.1.17:8080/hub.html?room=testroom
```

**Comment by rajnikantmrao** [comment]
Hmm. Should have tried that myself. My bad. Yup, it seems to be fetching the packages. Worked!

I was keen to check out the screen share component. 

Thanks

**Comment by robertlong** [comment]
Awesome! Let us know if you have any more questions. For stuff like this it's probably easier to reach us in the #social channel of the WebVR Slack.

https://slacknow.herokuapp.com/webvr

**Comment by rajnikantmrao** [comment]
Sure. Will do right away. Btw, I have been interacting with you on the aframe channel (handle:RR). :-)

My focus is using webVR is for training of all forms and screen share will be of great help

Thanks
