### ISSUE TITLE
zombie avatars remaining on leave

### ISSUE THREAD

**Issue by gfodor** [mozilla/mr-social-client#21]
when users leave the room, sometimes their  avatars remain. likely call stack: https://mozilla.slack.com/files/U723XJLDP/F835ECFCY/image.png

**Comment by brianpeiris** [comment]
I haven't seen this lately. We can track it again in Jira if it becomes a problem.

**Comment by gfodor** [comment]
I def saw this a few times today sadly :(

**Comment by mauriciomartinez-itesm** [comment]
This still happens sometimes
