### ISSUE TITLE
Virtual joystick center position is offset from visual representation

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/mr-social-client#31]
The actual center of the virtual joysticks are nearer to the corners of the screen than the visual circles.

**Comment by robertlong** [comment]
Hmm, I'm having trouble replicating this on my iPhone X and Pixel 2 XL. What device are you seeing this on?

**Comment by gfodor** [comment]
Probably can be dropped in favor of https://github.com/mozilla/mr-social-client/issues/84
