### ISSUE TITLE
Avatar heads do not appear in Firefox on Android

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/mr-social-client#32]

**Comment by brianpeiris** [comment]
Apparently only happens on (my?) Galaxy S6

**Comment by robertlong** [comment]
This is due to the skinned mesh used for the eyes right?

**Comment by brianpeiris** [comment]
Yup. We were only able to repro on S6 devices. Something about Firefox's webgl being incompatible with the GPU, I guess. Chrome does not repro it on the S6.

**Comment by brianpeiris** [comment]
I dug deeper into this issue. It looks like three.js skinned meshes do not work at all on the Galaxy S6. https://threejs.org/examples/webgl_skinning_simple.html

This seems to have broken in r85, when the implementation switched to using vertex textures.

https://cdn.rawgit.com/mrdoob/three.js/r84/examples/webgl_skinning_simple.html
https://cdn.rawgit.com/mrdoob/three.js/r85/examples/webgl_skinning_simple.html

In the end it seems to boil down to Firefox incorrectly reporting support for the OES_texture_float extension. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1338656

I'll try to work around this.
