### ISSUE TITLE
Disable microphone when navigating away from the app

### ISSUE THREAD

**Issue by robertlong** [mozilla/mr-social-client#51]
Currently on mobile, the microphone is left enabled when you navigate away from the app. This is good behavior in apps where you are having a conference call and multitasking, however I don't think its the same for our app.

We should disable the microphone or disconnect the user from Networked AFrame when navigating away from the application on mobile. We can probably use `window.onblur` on mobile only.

**Comment by netpro2k** [comment]
This is maybe desirable on mobile, but definitely not on desktop when screen sharing.

**Comment by brianpeiris** [comment]
Moved to SOCIAL-54
