### ISSUE TITLE
Yarn install fails on WSL

### ISSUE THREAD

**Issue by InfiniteLee** [mozilla/mr-social-client#7]
see: https://github.com/Microsoft/WSL/issues/2448 for issue and workaround

**Comment by netpro2k** [comment]
Closing this since a WSL issue and there is nothing we can do about it from our end.

**Comment by InfiniteLee** [comment]
I disagree- this should remain open as long as there is no fix in place- so that anyone else who runs into this can see this issue and know to use a workaround solution.
