### ISSUE TITLE
Asset Versioning and LODs

### ISSUE THREAD

**Issue by robertlong** [mozilla/mr-social-client#73]
Assets currently use a high quality and low quality url. There also isn't a great way to version them.

@gfodor @netpro2k @j-conrad @brianpeiris and I talked a bit about this in [this slack thread](https://webvr.slack.com/archives/C7Y55UC4S/p1521235494000288)

Here are some highlights:

Greg proposed an asset manifest file format that includes both versioning and LOD information:
```
http://duck.mozilla.com/assets/avatars/robot.XXX
http://duck.mozilla.com/assets/avatars/robot-0.1.0.XXX
{
  "name": "robot",
  "version": "0.1.0",
  "layers": [
    {
      "name": "base",
      "bundles": [
        { id: "robot-1", url: "https://duck.mozilla.com/assets/robot-desktop-0.3.4.glb" },
        { id: "robot-2", url: "https://duck.mozilla.com/assets/robot-mobile-0.3.4.glb" }
      ]
    }
  ],
  "hints": {
    "mobile-gen-1": ["base.robot-1"]
  }
}
http://duck.mozilla.com/assets/scenes/conference-room.XXX
http://duck.mozilla.com/assets/scenes/conference-room-0.2.0.XXX
{
  "name": "conference-room",
  "version": "0.2.0",
  "layers": [
    {
      "name": "environment",
      "bundles": [
        { id: "room-1", url: "https://duck.mozilla.com/assets/room-desktop-0.3.4.glb" },
        { id: "room-2", url: "https://duck.mozilla.com/assets/room-mobile-0.3.4.glb" }
      ]
    },
    {
      "name": "spawn-points",
      "bundles": [
        { id: "room-spawn", url: "https://duck.mozilla.com/assets/room-spawn-0.1.4.glb" }
      ]
    },
    {
      "name": "duck-interactables",
      "bundles": [
        { id: "room-ducks-1", url: "https://duck.mozilla.com/assets/room-ducks-desktop-0.0.4.glb" },
        { id: "room-ducks-2", url: "https://duck.mozilla.com/assets/room-ducks-mobile-0.0.4.glb" }
      ]
    }
  ],
  "hints": {
    "mobile-gen-1": ["environment.room-2", "duck-interactables.room-ducks-2"],
    "far-draw-distance": ["environment.room-2"]
  }
}
```

Dom proposed using [Microsoft's LOD glTF extension](https://github.com/sbtron/glTF/tree/MSFT_lod/extensions/Vendor/MSFT_lod)

Brian and I liked the idea of using .gltf instead of .glb for situations where you have shared assets. Ex. our avatars that only swap one texture between variants. Everything that is shared between the assets will be fetched from the cache.

We decided to delay working on this until after we have a few finished environments and avatars.

**Comment by gfodor** [comment]
I ended up needing to implement this for dynamic environment loading, since our environments have multiple glb files. Will share a PR soon.

**Comment by robertlong** [comment]
I think we can close this in favor of: https://github.com/mozilla/mr-social-client/issues/144

The asset bundles/MOZ_alt_materials work has been merged already, we just need to get templates working with them.
