### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by gfodor** [mozilla/mr-social-client#83]
For initial OKR metrics tracking and error handling, we should transition to using Google Analytics (which is sanctioned by Mozilla.)

**Comment by larsbergstrom** [comment]
Please make sure to request a GA tag internally to ensure it's got all the right settings (respecting user privacy, etc.) - we have somewhat stricter policies than the default GA settings. Myself / @cvan can help with instructions!

**Comment by larsbergstrom** [comment]
Also, please add myself and Andre Vrignaud when you request it :-)

**Comment by gfodor** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1449676

**Comment by cvan** [comment]
@gfodor: thanks for filing the Bugzilla bug.

- Mozilla Ops and the Data teams actually prefer bugs to be public (not Mozilla Confidential) when possible (unless PII, NDAs, or Product Strategy are involved).
- I can't edit the bug title, but you should explicitly request `360 GA`, not just normal `GA`.
- Also in the bug title: ask for a new `Property Tracking ID` not a new `Tag` (they are different)

**Comment by gfodor** [comment]
cool thanks. i made the ticket private because it includes info about product roadmap -- i'll make those other changes, thanks!

**Comment by gfodor** [comment]
Decided we're going to avoid introducing GA at this stage, since we can track OKRs directly without it.
