### ISSUE TITLE
Disable microphone on mobile when navigating away from app

### ISSUE THREAD

**Issue by gfodor** [mozilla/mr-social-client#91]
Currently on mobile, the microphone is left enabled when you navigate away from the app. This is good behavior in apps where you are having a conference call and multitasking, however I don't think its the same for our app.

We should disable the microphone or disconnect the user from Networked AFrame when navigating away from the application on mobile. We can probably use window.onblur on mobile only.

This is maybe desirable on mobile, but definitely not on desktop when screen sharing.

**Comment by netpro2k** [comment]
Biggest concern for me here would be false positives to due with the VR entry flow, i'm sure the browser loses focus for variable ammounts of time as part of that.

**Comment by robertlong** [comment]
What about a 10 second grace period before disconnecting?

We set a timeout for 10 seconds on any blur event on mobile. If we regain focus within 10 seconds we cancel the timeout.

Maybe 10 seconds is too short? Sometimes I lose my daydream controller and have to go find it. In that case you'll see the exited screen which will tell you to refresh your browser. That seems like good enough UX for now. It's the most privacy sensitive option but does degrade the UX if you can't enter VR within the grace period.
